Controllers/InventarioLibrosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProyectoInicial.Models;
using ProyectoInicial.Services;

namespace ProyectoInicial.Controllers
{
    public class InventarioLibrosController : Controller
    {

        private readonly Iconsumo _consumo;

        public InventarioLibrosController(Iconsumo consumo)
        {
            _consumo = consumo;
        }


        // GET: ProductoController
        public async Task<IActionResult> Index()
        {
            List<Libros> libros = await _consumo.GetLibros();
            return View(libros);
        }

        // GET: ProductoController/Details/5
        public async Task<IActionResult> Details(int IdLibro)
        {
            Libros DetalleLibro = new Libros();
            DetalleLibro = await _consumo.GetLibro(IdLibro);
            if (DetalleLibro != null)
            {
                return View(DetalleLibro);
            }
            return RedirectToAction("Index");
        }

        // GET: ProductoController/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Libros libro)
        {
            
                Libros libroCreado = await _consumo.PostLibro(libro);
                return RedirectToAction("Index");
            
        }



        // GET: ProductoController/Edit/5
        public async Task<IActionResult> Edit(int IdLibro)
        {
            
            Libros libroEditado = await _consumo.GetLibro(IdLibro);
            return View(libroEditado);
            
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Libros libro)
        {
            //try
            //{
            if (libro.IdLibro == 0)
            {
                Libros libroEditado = await _consumo.PostLibro(libro);
            }
            else
            {
                Libros libroEditado = await _consumo.PutLibro(libro.IdLibro, libro);

            }
            return RedirectToAction("Index");
            
        }



        [HttpGet]
        // GET: ProductoController/Delete/5
        public async Task<IActionResult> Delete(int IdLibro)
        {
            
                string result = await _consumo.DeleteLibro(IdLibro);
                return RedirectToAction("Index");
           
             
        }



    }
}

Controllers/PrestamoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProyectoInicial.Models;
using ProyectoInicial.Services;

namespace ProyectoInicial.Controllers
{
    public class PrestamoController : Controller
    {
        private readonly Iconsumo _consumo;

        public PrestamoController(Iconsumo consumo)
        {
            _consumo = consumo;
        }


        public async Task<IActionResult> Index()
        {
            List<Prestamo> prestamo = await _consumo.GetPrestamos();
            return View(prestamo);
        }

        public async Task<IActionResult> Details(int IdPrestamo)
        {
            Prestamo DetallePrestamo = new Prestamo();
            DetallePrestamo = await _consumo.GetPrestamo(IdPrestamo);
            if (DetallePrestamo != null)
            {
                return View(DetallePrestamo);
            }
            return RedirectToAction("Index");
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Prestamo prestamo)
        {
            Libros libroPrestado = await _consumo.GetLibro(prestamo.IdProducto);
            prestamo.PrecioUnitario = libroPrestado.precio;
            if (prestamo.Cantidad <= libroPrestado.cantidad)
            {
                libroPrestado.cantidad = libroPrestado.cantidad - prestamo.Cantidad;
                
                await _consumo.PutLibro(libroPrestado.IdLibro, libroPrestado);
                Prestamo prestamoCreado = await _consumo.PostPrestamo(prestamo);
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
            

        }

        public async Task<IActionResult> Edit(int IdPrestamo)
        {

            Prestamo prestamoEditado = await _consumo.GetPrestamo(IdPrestamo);
            return View(prestamoEditado);

        }

        [HttpPost]
        public async Task<IActionResult> Edit(Prestamo prestamo)
        {
            
            if (prestamo.IdPrestamo == 0)
            {
                Prestamo prestamoEditado = await _consumo.PostPrestamo(prestamo);
            }
            else
            {
                Prestamo prestamoEditado = await _consumo.PutPrestamo(prestamo.IdPrestamo,prestamo);
               

            }
            return RedirectToAction("Index");

        }



        [HttpGet]

        public async Task<IActionResult> Delete(int IdPrestamo)
        {

            string result = await _consumo.DeletePrestamo(IdPrestamo);
            return RedirectToAction("Index");


        }

    }
}

Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProyectoInicial.Models;
using ProyectoInicial.Services;

namespace ProyectoInicial.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly Iconsumo _consumo;

        public UsuarioController(Iconsumo consumo)
        {
            _consumo = consumo;
        }


        // GET: ProductoController
        public async Task<IActionResult> Index()
        {
            List<Usuario> usuarios = await _consumo.GetUsuarios();
            return View(usuarios);
        }

        // GET: ProductoController/Details/5
        /*public async Task<IActionResult> Details(int IdUsuario)
        {
            Usuario DetalleUsuario = new Usuario();
            DetalleUsuario = await _consumo.GetUsuario(IdUsuario);
            if (DetalleUsuario != null)
            {
                return View(DetalleUsuario);
            }
            return RedirectToAction("Index");
        }*/

        // GET: ProductoController/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Usuario usuario)
        {
            List<Usuario> usuarios=await _consumo.GetUsuarios();
            bool credencialesValidas = usuarios.Any(u => u.UsuarioP == usuario.UsuarioP );

            if (credencialesValidas)
            {
                //ViewData["Mensaje"] = "No se pudo crear el usuario";
                return View();
            }
            else
            {
                Usuario usuarioCreado = await _consumo.PostUsuario(usuario);
                return RedirectToAction("Index");

            }
        }
        public async Task<IActionResult> Edit(int IdUsuario)
        {

            Usuario usuarioEditado = await _consumo.GetUsuario(IdUsuario);
            return View(usuarioEditado);

        }

        [HttpPost]
        public async Task<IActionResult> Edit(Usuario usuario)
        {
            //try
            //{
            if (usuario.IdUsuario == 0)
            {
                Usuario usuarioEditado = await _consumo.PostUsuario(usuario);
            }
            else
            {
                Usuario usuarioEditado = await _consumo.PutUsuario(usuario.IdUsuario, usuario);

            }
            return RedirectToAction("Index");

        }



        [HttpGet]

        public async Task<IActionResult> Delete(int IdUsuario)
        {

            string result = await _consumo.DeleteUsuario(IdUsuario);
            return RedirectToAction("Index");


        }


    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Biblioteca</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProyectoInicial.styles.css" asp-append-version="true" />
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-green border-bottom box-shadow mb-3 ">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Cliente" asp-action="Index"><img src="https://openclipart.org/image/2400px/svg_to_png/275692/1489798288.png" width="100" height="80" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!-- ... Código anterior ... -->

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="button-30" role="button" Button 30, asp-controller="InventarioLibros" asp-action="Index">Libros</a>
                        </li>
                        <li class="nav-item">
                            <a class="button-30" role="button" Button 30, asp-controller="Usuario" asp-action="Index">Usuarios Prueba</a>
                        </li>
                        <li class="nav-item">
                            <a class="button-30" role="button" Button 30, asp-controller="Prestamo" asp-action="Index">Prestamos</a>
                        </li>
                        <li class="nav-item" style="margin-left: auto;">
                            <a class="button-30" role="button" asp-controller="Home" asp-action="Index">Cerrar Sesion</a>
                        </li>
                    </ul>
                </div>

                <!-- ... Código posterior ... -->

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-black">
        <div class="container">
            &copy; 2023 - ProyectoInicial - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>